## **POPULARITY BASED RECOMMENDATIONS ENGINE**

Popularity based recommender are a primitive form of collaborative based filtering recommendations system which recommend items based on its popularity among previous users i.e. it makes recommendations based on the ratings of other users. 

These datasets are hosted on: https://archive.ics.uci.edu/ml/datasets/Restaurant+%26+consumer+data

They were originally published by: Blanca Vargas-Govea, Juan Gabriel GonzÃ¡lez-Serna, Rafael Ponce-MedellÃ­n. Effects of relevant contextual features in the performance of a restaurant recommender system. In RecSysâ€™11: Workshop on Context Aware Recommender Systems (CARS-2011), Chicago, IL, USA, October 23, 2011.

**Dependencies**

In [2]:
import pandas as pd
import numpy as np

In [3]:
ratings = pd.read_csv('rating_final.csv')

cuisines = pd.read_csv('chefmozcuisine.csv')

**Exploratory Data Analysis**

In [48]:
ratings.describe()

placeID       rating  food_rating  service_rating
count    1161.000000  1161.000000  1161.000000     1161.000000
mean   134192.041344     1.199828     1.215332        1.090439
std      1100.916275     0.773282     0.792294        0.790844
min    132560.000000     0.000000     0.000000        0.000000
25%    132856.000000     1.000000     1.000000        0.000000
50%    135030.000000     1.000000     1.000000        1.000000
75%    135059.000000     2.000000     2.000000        2.000000
max    135109.000000     2.000000     2.000000        2.000000

**NB**

Maximum value of all ratings in the dataset was 2. Therefore it is possible that the only values available to select were 1 or 2

In [60]:
length_of_restaurants = len(ratings['placeID'].unique())
print(f'Total number of restaurants : {length_of_restaurants}')

Total number of restaurants : 130


In [61]:
ratings.head()

userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [5]:
cuisines.head()

placeID        Rcuisine
0   135110         Spanish
1   135109         Italian
2   135107  Latin_American
3   135106         Mexican
4   135105       Fast_Food

**Recommending restaurant based on counts of user ratings**

In [11]:
#group ratings by placeID of restaurant
ratings_count = pd.DataFrame(ratings.groupby(by = 'placeID')['rating'].count())

ratings_count.sort_values(by = 'rating', ascending = False ).head()

rating
placeID        
135085       36
132825       32
135032       28
135052       25
132834       25

Restaurant with placeID of 135085 is the restaurant with the rating counts. It is therefore the recommended restaurant based on counts of user ratings

**Recommending restaurant based on average user rating**

In [14]:
ratings_avg = pd.DataFrame(data = ratings.groupby('placeID')['rating'].mean())

ratings_avg.sort_values(by = 'rating', ascending = False).head()

rating
placeID          
132955   2.000000
135034   2.000000
134986   2.000000
132922   1.833333
132755   1.800000

Restaurants with placeID of 132955, 135034,134986 are the restaurant with the highest number of average ratings. they are therefore the recommended restaurants based on average restaurant ratings.

The same process can be carried out to recommend based on food_rating and service_rating

**Recommending best food to eat in recommended restaurants based on counts of user rating**

In [46]:
#create dataframe to hold placeID's of top 5 recommended restaurants
best_food_on_sum = pd.DataFrame([135085, 132825, 135032, 135052, 132834], columns=['placeID'])

#create dataframe and merge best_food_on_sum with cuisines
summary_on_sum = pd.merge(best_food_on_sum, cuisines, on='placeID')
summary_on_sum

placeID         Rcuisine
0   135085        Fast_Food
1   132825          Mexican
2   135032        Cafeteria
3   135032     Contemporary
4   135052              Bar
5   135052  Bar_Pub_Brewery
6   132834          Mexican

In [47]:
summary_on_sum['Rcuisine'].describe()

count           7
unique          6
top       Mexican
freq            2
Name: Rcuisine, dtype: object

**Recommending best food to eat in recommended restaurants based on average of user rating**

In [44]:
best_food_on_avg = pd.DataFrame([132955, 135034, 134986, 132922, 132755], index=np.arange(5), columns=['placeID'])

summary_on_avg = pd.merge(best_food_on_avg, cuisines, on='placeID')
summary_on_avg

placeID         Rcuisine
0   132955  Bar_Pub_Brewery
1   135034         Japanese
2   134986    International
3   132922        Cafeteria
4   132755          Mexican

In [45]:
summary_on_avg['Rcuisine'].describe()

count            5
unique           5
top       Japanese
freq             1
Name: Rcuisine, dtype: object